env:
  es6: true
  node: true
  browser: true
extends: ['eslint:recommended', 'plugin:react/recommended']
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 5
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  consistent-return:
    - error
  prefer-arrow-callback:
    - error
  no-spaced-func:
    - error
  no-trailing-spaces:
    - error
  object-curly-spacing:
    - error
    - always
  spaced-comment:
    - error
    - always
  arrow-spacing:
    - error
  no-redeclare:
    - error
